[package]
name = "grovedb-commitment-tree"
description = "Orchard-style commitment tree integration for GroveDB"
version = "4.0.0"
authors = ["Samuel Westrich <sam@dash.org>"]
edition = "2021"
license = "MIT"
homepage = "https://www.grovedb.org"
repository = "https://github.com/dashpay/grovedb"
readme = "../README.md"
documentation = "https://docs.rs/grovedb"

[dependencies]
orchard = { version = "0.12", features = ["circuit"] }
incrementalmerkletree = "0.8"
shardtree = "0.6"
pasta_curves = "0.5"
thiserror = "2.0"
