[package]
name = "grovedb-costs"
version = "2.0.3"
edition = "2021"
license = "MIT"
description = "Costs extension crate for GroveDB"
homepage = "https://www.grovedb.org/"
documentation = "https://docs.rs/grovedb-costs"
repository = "https://github.com/dashpay/grovedb"


[dependencies]
thiserror = "1.0.59"
intmap = "2.0.0"
integer-encoding = "4.0.0"
