[package]
name = "grovedb-version"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Versioning library for Platform"
version = "1.1.0"
edition = "2021"
license = "MIT"

[dependencies]
thiserror = "1.0.59"
versioned-feature-core = "1.0.0"

[features]
mock-versions = []
